version: '3'
services:
  api:
    build: .
    environment: 
      - DB_USERNAME=root
      - DB_PASSWORD=hunter2
      - DB_HOSTNAME=mongodb
      - DB_PORT=27017
      - DB_NAME=final-project
      - REDIS_HOST=redis
      - REDIS_USER=default
      - REDIS_PASSWORD=hunter2
      - REDIS_PORT=6379
      - PORT=8000
    ports:
      - 8000:8000

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
      - MONGO_INITDB_DATABASE=final-project
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=hunter2
    ports: # this is removable in production building
      - 27017:27017

  db-init:
    build: .
    environment:
      - DB_HOSTNAME=mongodb
      - DB_USERNAME=root
      - DB_PASSWORD=hunter2
      - DB_NAME=final-project
    depends_on:
      - mongodb
    restart: on-failure
    command: npm run initdb
      

  redis:
    image: redis:latest
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 6379:6379 

